#!/usr/bin/env Rscript

# Source the plotting script
source("code/plotting.R")

# Main function of frequency analyze
analyze_frequency <- function(date_hour) {
  
  # Read data words
  file_name <- paste0("output/words_", date_hour, ".txt")
  
  # Load the table generated by the second script
  data_words <- read.table(file_name, sep = "\t", header = TRUE)
  
  # Count term frequency in each book
  docs_words <- data_words %>% 
    count(document, word, sort = TRUE)
  
  # Count number of terms in each book
  total_words <- docs_words %>% 
    group_by(document) %>% 
    summarize(total = sum(n))
  
  # Join both
  docs_words <- left_join(docs_words, total_words, by = "document")
  
  # Plot term frequency distribution
  term_frequency_plot <- plot_term_frequency(docs_words, title="Distribución de Frecuencia de Términos", xlab="Frecuencia de Términos", ylab="Conteo")
  #save_plot_to_pdf(term_frequency_plot, paste0("output/term_frequency_", date_hour, ".pdf"))

  # Plot yearly frequency for all words
  # yearly_frequency_plot <- plot_yearly_frequency(data_words, title="Frecuencia Anual de Todas las Palabras", xlab="Año", ylab="Frecuencia")
  # print(yearly_frequency_plot)
  # save_plot_to_pdf(yearly_frequency_plot, paste0("output/yearly_frequency_", date_hour, ".pdf"))
  
  # Apply Zipf's Law and plot
  zipfs_law_plot <- plot_zipfs_law(docs_words, title="Ley de Zipf", xlab="Rango", ylab="Frecuencia de Término")
  #save_plot_to_pdf(zipfs_law_plot, paste0("output/zipfs_law_", date_hour, ".pdf"))
  
  # Calculate TF-IDF and plot
  docs_words <- docs_words %>%
    bind_tf_idf(word, document, n)
  tf_idf_plot <- plot_tf_idf(docs_words, title="Top 10 Palabras por TF-IDF", xlab=NULL, ylab="tf-idf")
  #save_plot_to_pdf(tf_idf_plot, paste0("output/tf_idf_", date_hour, ".pdf"))
}
