#!/usr/bin/env Rscript

main_process_texts <- function(directory, language, ngram_number, date_hour) {
# # Verify that the necessary arguments have been specified
# args <- commandArgs(trailingOnly = TRUE)

# if (length(args) != 4) {
#   stop("Use program: path/of/file path/of/keywords.txt and SP or EN and number of ngram(separated by space)")
# }

# Necessary libraries
# required_packages <- c("tidytext", "tidyverse")

# for (pkg in required_packages) {
#   if (!requireNamespace(pkg, quietly = TRUE)) {
#     install.packages(pkg)
#   }
#   library(pkg, character.only = TRUE)
# }

# Function to remove accent marks from a text
remove_accents <- function(texto) {
  iconv(texto, to = "ASCII//TRANSLIT")
}

#setwd("/home/usuario/Data_Rstudio/sofiaBausero/CategoricalAndTrendanalysis/")

# Cargará todos los ficheros de los mensajes
#files <- list.files(path = args[1], pattern = "\\d+")# "datos/actas" ## cambiar esto!!

file_name <- paste0("code/data_table_", date_hour, ".txt")

# Load the table generated by the second script
data_table <- read.table(file_name, sep = "\t", header = FALSE, col.names = c("space", "number"))


# Format the dates in the 'number' column from "dd/mm/yyyy" to "dd-mm-yyyy"
data_table$number <- gsub("/", "-", data_table$number)

# Basename
data_table$space <- basename(data_table$space)
data_table$origin_space <- data_table$space

# Removed tag
data_table$space <- gsub("\\.[^.]+$", "", data_table$space)

# Cargar los ficheros de los mensajes
# files <- list.files(path = args[1], pattern = "\\d+")
# number <- as.numeric(gsub("[^0-9]", "", files))
# space <- gsub("[0-9_\\]", "", files)
# space <- gsub("\\.txt$", "", space)

# IF is numeric, is numeric, else is character, is character add conditional!
infoText <- if (is.numeric(data_table$number[1])) {
  tibble(
    number = numeric(),
    space = character(),
    paragraph = numeric(),
    text = character()
  )
} else {
  tibble(
    number = character(),
    space = character(),
    paragraph = numeric(),
    text = character()
  )
}

# Read the files and create the initial tibble
for (i in seq_along(data_table$origin_space)) {
  speech <- readLines(file.path(directory, data_table$origin_space[i]))
  temporal <- tibble(number = data_table$number[i],
                     space = data_table$space[i],
                     paragraph = seq_along(speech),
                     text = speech)
  infoText <- bind_rows(infoText, temporal)
}

infoText <- infoText %>%
  mutate(space = factor(space, levels = unique(space)),
         number = factor(number))

# Read stop words according to the specified language
if (tolower(language) == "sp") {
  empty <- read_tsv("datos/vacias.txt", col_names = "word")
} else if (tolower(language) == "en") {
  empty <- stop_words %>% select(word)
} else {
  stop("Invalid language argument. Use 'SP' or 'EN'.")
}

# Function to generate tokens and filter ngrams
generate_ngrams <- function(infoText, n) {
  tokens <- infoText %>%
    unnest_tokens(word, text, token = "ngrams", n = n) %>%
    separate(word, into = paste0("word", 1:n), sep = " ") %>%
    filter(across(starts_with("word"), ~ !grepl("\\d+", .) & !(. %in% empty$word))) %>%
    unite(word, starts_with("word"), sep = " ")
  
  return(tokens)
}

# Generate the ngrams and filter
if (ngram_number == "3") {
  infoText_token <- generate_ngrams(infoText, 3)
} else if (ngram_number == "2") {
  infoText_token <- generate_ngrams(infoText, 2)
} else if (ngram_number == "1" || ngram_number == "") {
  infoText_token <- infoText %>%
    unnest_tokens(word, text) %>%
    filter(!grepl("\\d+", word) & !word %in% empty$word)
} else {
  stop("Invalid ngram value. Use 1, 2, or 3.")
}

# Save the result to a file
output_dir <- "datos/outputData"
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

#
#date_hour <- format(Sys.time(), "%d-%m-%Y_%H-%M")
# date_hour <-  args[4]
textWord <- file.path("datos/outputData", paste0("words_", date_hour, ".txt"))
write.table(infoText_token, file = textWord, row.names = FALSE, col.names = TRUE, sep = "\t", quote = FALSE)

}

# # Call the main function if the script is run directly
# if (!interactive()) {
#   args <- commandArgs(trailingOnly = TRUE)
#   if (length(args) != 4) {
#     stop("Use program: path/of/file and SP or EN and number of ngram (separated by space)")
#   }
#   directory <- args[1]
#   #keywords_path <- args[2]
#   language <- args[2]
#   ngram <- as.numeric(args[3])
#   date_hour <- args[4]
#   main_process_texts(directory, language, ngram, date_hour)
# }
## WE NEED FIX THIS PROBLEM